name: Arduino workflow

on:
  repository_dispatch:
    types: do-notify

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Notify
      run: echo "Content ${{ github.event.client_payload.content }}"
